name: marcacao_de_presenca
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # utilities packeges
  http: ^1.1.0
  connectivity_plus: ^5.0.2
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.2.2
  smooth_page_indicator: ^1.1.0
  iconify_flutter: ^0.0.5
  google_fonts: ^6.1.0
  dropdown_button2: ^2.3.8
  flutter_barcode_scanner: ^2.0.0
  geolocator: ^10.1.0
  shared_preferences: ^2.0.8
  local_auth: ^2.1.7
  pretty_qr_code: ^3.0.0
  barcode_widget: ^2.0.4
  pdf: ^3.10.7
  qr_flutter: ^4.1.0
  image: ^4.1.3
  open_file: ^3.3.2
  path_provider: ^2.1.1
  printing: ^5.11.1
  screenshot: ^2.1.0
  json_serializable: ^6.7.1
  lottie: ^2.7.0

  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  # state Manegement
  get: ^4.6.5
  get_storage: 2.1.1
  sqflite: ^2.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/logos/
    - assets/imagens/animations/
    - assets/imagens/background/
    - assets/icons/
    - assets/imagens/alunos/
    

  fonts:
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Light.ttf
        - weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
        - weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
        - style:  italic
        - asset: assets/fonts/Poppins-Medium.ttf
        - weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - weight: 500
        - style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
        - weight: 700
        
        
        